trigger:
- master

pool:
  name: Desktop-dell

stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontendApp
    strategy:
     parallel: 2
    displayName: Build Frontend App
    steps:
    - script: echo building frontend app
      displayName: build frontend app
    - script: echo running unit tests for frontend app
      displayName: unit tests frontend

  - job: BuildBackendApp
    strategy:
     parallel: 2
    displayName: Build Backend App
    steps:
    - script: echo building backend app
      displayName: build backend app
    - script: echo running unit tests for backend app
      displayName: unit tests backend

- stage: DeployDev
  displayName: Deploy to DEV environment
  jobs:
  - job: DeployFrontendDev
    strategy:
     parallel: 2
    displayName: Deploy frontend to DEV
    steps:
    - script: echo deploying frontend app to DEV
      displayName: deploy frontend app to DEV

  - job: DeployBackendDev
    strategy:
     parallel: 2
    displayName: Deploy backend to DEV
    steps:
    - script: echo deploying backend app to DEV
      displayName: deploy backend app to DEV

